version: '3.8'

services:
  # Laravel Application
  laravel:
    build:
      context: ./laravel-blog
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./laravel-blog:/var/www/html
      - ./laravel-blog/storage:/var/www/html/storage
      - ./laravel-blog/bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - CHATBOT_API_URL=http://chatbot:8000
    depends_on:
      - chatbot
    networks:
      - app-network

  # Ollama AI Model Service
  ollama:
    build: ./ollama
    container_name: ollama
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  # AI Chatbot FastAPI Service
  chatbot:
    build: ./chatbot
    container_name: chatbot
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./chatbot:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    networks:
      - app-network

volumes:
  ollama_models:

networks:
  app-network:
    driver: bridge