services:
  # Ollama service (AI model)
  ollama:
    image: ollama/ollama:latest
    container_name: gamma_ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    networks:
      - gamma_network

  # FastAPI backend
  fastapi:
    build: 
      context: ./Gamma_Chatbot
      dockerfile: Dockerfile
    container_name: gamma_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    networks:
      - gamma_network
    volumes:
      - ./Gamma_Chatbot/app:/app

  # Laravel frontend
  laravel:
    build:
      context: ./gamma-laravel-frontend
      dockerfile: Dockerfile
    container_name: gamma_laravel
    ports:
      - "8080:80"
    depends_on:
      - fastapi
    environment:
      - FASTAPI_URL=http://fastapi:8000
      - APP_ENV=production
      - APP_DEBUG=false
    restart: unless-stopped
    networks:
      - gamma_network

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: gamma_nginx
    ports:
      - "80:80"
    depends_on:
      - laravel
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - gamma_network

volumes:
  ollama_data:

networks:
  gamma_network:
    driver: bridge